name: Build LaTeX Files to fsoc.space
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Build .tex files
        uses: fs-c/latex-action@master
        with:
          root_file: ./**/*.tex
          glob_root_file: true
          work_in_root_file_dir: true
          continue_on_error: true
      - name: Upload artifact for testing
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: ./**/*.pdf
      - name: Remove all non-PDF files
        run: |
          find . -type f ! -name '*.pdf' -delete
      - name: Push output to fsoc.space
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.FSOCSPACE_SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: fs-c
          destination-repository-name: fsoc.space
          target-branch: workbench
          target-directory: public/jku
