name: Build LaTeX Files to files repo
on:
  push:
    branches:
      - master
    paths:
      - '**.tex'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Build .tex files
        uses: fs-c/latex-action@master
        with:
          root_file: ./**/*.tex
          glob_root_file: true
          work_in_root_file_dir: true
          continue_on_error: true
      - name: Remove all non-PDF files
        run: |
          find . -type f ! -name '*.pdf' -delete
      - name: Push output to files repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.FILES_SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: fs-c
          destination-repository-name: files
          target-branch: archive
          target-directory: jku/build
