name: Build LaTeX Files to PDF
on: [push]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Build .tex files
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "2021w/dstrukt/blatt1.tex"
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Upload artifact for testing
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: "**/*.pdf"
